### ISSUE TITLE
Code Optimization

### ISSUE THREAD

**Issue by Rahulbaran** [Diplocity/Diplocity.github.io#58]
Hey Abenezer
May I optimize your code and make it cleaner??

**Comment by Diplocity** [comment]
Hello Sir
I actually needed someone who could assist me in my site and also teaching
me how to edit the CSS and JavaScript on it so it will really be a great
pleasure of mine, how can you access the repository? This is the site:
Diplocity.github.io

Best Regards
Ebenezer

**Comment by Rahulbaran** [comment]
Ebenezer, let's do this together. I will guide you about how to optimize ze

**Comment by Rahulbaran** [comment]
Let me know if you can start now

**Comment by Diplocity** [comment]
That's great Kumar we can start immediately 😊, I am currently trying to build a gallery for my designing projects as you can see

**Comment by Rahulbaran** [comment]
Can we connect on **Discord**?? It will be easier to move

**Comment by Diplocity** [comment]
Okay Rahul thanks, is discord an app?

**Comment by Rahulbaran** [comment]
Yeah, it is a great platform to connect with people.

**Comment by Rahulbaran** [comment]
You can join various communities on discord.

**Comment by Diplocity** [comment]
Okay I just downloaded discord

**Comment by Rahulbaran** [comment]
I will also recommend to use twitter. twitter and discord both are great platforms to connect with developers around the world.

**Comment by Rahulbaran** [comment]
We can join these communities on discord

- [EddieHub](https://discord.gg/9u4hGtN9)
- [Kevin Powell](https://discord.gg/kevinpowell)
- [Commit Your Code](https://discord.gg/kevinpowell)

**Comment by Diplocity** [comment]
I have joined the groups, can you edit the form for me with CSS and also the gallery.

**Comment by Diplocity** [comment]
Hi Rahul, I am trying to create a my designs section for the site and I got some code on codepen to do that, can you please teach me how to edit the site with it and also how to use JavaScript for it, thanks.

**Comment by Rahulbaran** [comment]
Send the link and I will check it.

**Comment by Diplocity** [comment]
https://codepen.io/humbl3man/pen/NWEOLy

This is the gallery i am trying to integrate to the site, yes i am learning alot.

**Comment by Diplocity** [comment]
https://codepen.io/humbl3man/pen/NWEOLy

this is the image slider i am trying to add to the site, at the my designs
section.
